### ISSUE TITLE
Vagrant is not fire up

### ISSUE THREAD

**Issue by AlexeyALeonov** [obfuscurity/synthesize#68] opened 2017-08-21 12:13 UTC
PS C:\Users\aleonov\Documents\DevOps\synthesize> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'mayflower/trusty64-puppet3' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'mayflower/trusty64-puppet3'
    default: URL: https://vagrantcloud.com/mayflower/trusty64-puppet3
==> default: Adding box 'mayflower/trusty64-puppet3' (v0.7.2) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/mayflower/boxes/trusty64-puppet3/versions/0.7.2/providers/virtualbox.
box
    default: Progress: 100% (Rate: 215/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to filedump.mayflower.de:443

**Comment by obfuscurity** [comment] 2017-10-09 12:17
Hi Alexey, apologies for the delayed response. This appears to be an issue with your OpenSSL (on Windows) version or perhaps a proxy issue. It seems that you're having an issue downloading the upstream Vagrant box, which I'm unable to reproduce. If you're still experiencing this I might be able to help narrow down the cause but I'll need more information (e.g. your OS version, any proxies in use, etc).

Closing this issue as unrelated to Synthesize for the time being.

**Closed by obfuscurity** 2017-10-09 12:17 UTC
