### ISSUE TITLE
Getting errors while installing graphite

### ISSUE THREAD

**Issue by praste** [obfuscurity/synthesize#29] opened 2015-03-18 17:11 UTC
I am getting following error while installing graphite
`````
gcc -o src/networking.o -c -g -std=c99 -D_GNU_SOURCE -O3 -pthread -Ideps/inih/ -Ideps/libev/ -Isrc/ src/networking.c
In file included from src/networking.c:30:0:
deps/libev/ev.c: In function 'pipecb':
deps/libev/ev.c:1896:16: warning: ignoring return value of 'read', declared with attribute warn_unused_result [-Wunused-result]
           read (evfd, &counter, sizeof (uint64_t));
                ^
deps/libev/ev.c:1903:16: warning: ignoring return value of 'read', declared with attribute warn_unused_result [-Wunused-result]
           read (evpipe [0], &dummy, 1);
                ^
deps/libev/ev.c: In function 'evpipe_write':
deps/libev/ev.c:1866:17: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
           write (evfd, &counter, sizeof (uint64_t));
                 ^
deps/libev/ev.c:1876:17: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
           write (evpipe [1], &(evpipe [1]), 1);
                 ^
gcc -o src/conn_handler.o -c -g -std=c99 -D_GNU_SOURCE -O3 -pthread -Ideps/inih/ -Ideps/libev/ -Isrc/ src/conn_handler.c
src/conn_handler.c: In function 'stream_formatter':
src/conn_handler.c:109:17: warning: format '%lld' expects argument of type 'long long int', but argument 5 has type 'uint64_t' [-Wformat=]
                 STREAM("%s%s.count|%lld|%lld\n", prefix, name, counter_count(value));
                 ^
src/conn_handler.c:123:13: warning: format '%lld' expects argument of type 'long long int', but argument 5 has type 'uint64_t' [-Wformat=]
             STREAM("%s%s|%lld|%lld\n", prefix, name, set_size(value));
             ^
src/conn_handler.c:133:13: warning: format '%lld' expects argument of type 'long long int', but argument 5 has type 'uint64_t' [-Wformat=]
             STREAM("%s%s.count|%lld|%lld\n", prefix, name, timer_count(&t->tm))
`````

and

`````
Installing custom SQL ...
Installing indexes ...
Problem installing fixture 'initial_data.json': Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 196, in handle
    obj.save(using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/core/serializers/base.py", line 165, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 529, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 557, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 986, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: Could not load contenttypes.ContentType(pk=9): UNIQUE constraint failed: django_content_type.app_
`````

**Comment by obfuscurity** [comment] 2015-03-18 17:14
Duplicate of #28. Thanks for reporting though, it's on my TODO to fix this ASAP.

**Closed by obfuscurity** 2015-03-18 17:14 UTC
